// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF2Mjoq6VxQvFscHnIzpS8Ycmc13ldLdQ',
    appId: '1:670875149682:web:1326f12a92468a293569eb',
    messagingSenderId: '670875149682',
    projectId: 'barberproject-446b1',
    authDomain: 'barberproject-446b1.firebaseapp.com',
    databaseURL: 'https://barberproject-446b1-default-rtdb.firebaseio.com',
    storageBucket: 'barberproject-446b1.appspot.com',
    measurementId: 'G-NWRS0871N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAECWJdhUwG3jA0tYnVEd0WBr0S00P6MT0',
    appId: '1:670875149682:android:a9c9b85b6cc1154f3569eb',
    messagingSenderId: '670875149682',
    projectId: 'barberproject-446b1',
    databaseURL: 'https://barberproject-446b1-default-rtdb.firebaseio.com',
    storageBucket: 'barberproject-446b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHQEq9Un0SILzCyXBHmn3Gt5aucQC7W5o',
    appId: '1:670875149682:ios:4c0ff52bb2994a3e3569eb',
    messagingSenderId: '670875149682',
    projectId: 'barberproject-446b1',
    databaseURL: 'https://barberproject-446b1-default-rtdb.firebaseio.com',
    storageBucket: 'barberproject-446b1.appspot.com',
    iosBundleId: 'com.example.updatedBarberProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHQEq9Un0SILzCyXBHmn3Gt5aucQC7W5o',
    appId: '1:670875149682:ios:47c5acca103424f73569eb',
    messagingSenderId: '670875149682',
    projectId: 'barberproject-446b1',
    databaseURL: 'https://barberproject-446b1-default-rtdb.firebaseio.com',
    storageBucket: 'barberproject-446b1.appspot.com',
    iosBundleId: 'com.example.updatedBarberProject.RunnerTests',
  );
}
